language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
services: mongodb
script: nosetests --with-coverage --cover-erase --cover-package=xunta --cover-html
after_success: coveralls
notifications:
  email: false
dd:
  secure: ffR+WkQvjcpOvrBfQv1dfcggAxNydrUDGJUG/kj343Odb7oCoEuO/+BUkGB2D09GP9PWD4n0TZ8NYN/HxiF60E8jzF7+EFcff51Xm2mggWyf1zFHBaoJnzsqQH+9NWAffRHuJFqRfhKZBChb7jIvfb4TVOi4M5dWQjIOQ3nmOVs=
env:
  global:
  - secure: J1IQs4UBYBNvtcyXQG/y/RxQjOYV7FIezLoKZfjGSIrhzNMPXgS0Zi3kwFHM/YiAAIZSWd5xWRa+uGuvfkNhAqjJsOYMobDFzhy7sCIGKWOfY3YJB4dke06ta5dMMtZhJgpWXeyd1GsFPiZiXTUX9A56v+/o9VX+bCKZ0d4nhrY=
  - secure: hWAU5CUYL7+PIVAlM5Rikwb8JZ8HB6OHr7ooe3igBJzdnnXIXGyZ2lOC2w3nH35Tst4O8ko29ItpZeXQXCA8HNpzTgI66wDEgc+wgMNURvzfhkGGr9rXCt4IzrHH5UXFzAJYMOQKNPwGhMhmiG5Ceyk8oYncPoqBksA/hNXdqCM=
